### PR TITLE
Do not fail on write error

### LINKED ISSUE #1505: UnsupportedOperationException fatal error when schema does not match
Hello, we are using Secor to parse JSON events using the JsonMessageParser, outputting to ORC files.

We encountered a fatal error the other day with an invalid event being present in the source topic, which contained a matching key name but had a different data type. The result was that the reader successfully parsed the message, but the writer failed and caused the following error:

image

It seems based on the implementation in [Consumer.java](https://github.com/pinterest/secor/blob/master/src/main/java/com/pinterest/secor/consumer/Consumer.java#L252), the intention is for Secor to skip messages that can't be parsed with a warning, but any write errors are rethrown. This caused Secor to get stuck on this one bad event and hold up the whole partition. Is this behaviour intentional or should it prevent a mismatch between reader and writer formats like this?

### PR DESCRIPTION
**Pull request by pdambrauskas**
Fixes #1505 

This issue occurred to us too. Found existing issue about it and made this PR.

- Moved offset parsing and message parsing to single `try/catch` block
- Reused fail backoff logic which was implemented in parse block
- Made fail threshold configurable
- Split `consumeNextMessage` to multiple smaller methods to make it more readable.

### CODE REVIEW

File: src/main/java/com/pinterest/secor/consumer/Consumer.java [hunk 1]
```diff
@@ -223,37 +224,12 @@ protected boolean consumeNextMessage() {
                 }
 
                 parsedMessage = mMessageParser.parse(transformedMessage);
-                final double DECAY = 0.999;
```
Comment (HenryCaiHaiying) [inline src/main/java/com/pinterest/secor/consumer/Consumer.java:226]: Did we lose the reset of DECAY after refactoring?

File: src/main/java/com/pinterest/secor/consumer/Consumer.java [hunk 2]
```diff
@@ -267,4 +243,36 @@ protected boolean consumeNextMessage() {
...
+        try {
+            mMessageWriter.adjustOffset(rawMessage, isLegacyConsumer);
+        } catch (IOException e) {
+            throw new RuntimeException("Failed to adjust offset.", e);
+        }
+    }
+
+    private void writeMessage(Message rawMessage, ParsedMessage parsedMessage) throws Exception {
+        mMessageWriter.write(parsedMessage);
+        mBadMessages *= DECAY;
```
Comment (pdambrauskas) [inline src/main/java/com/pinterest/secor/consumer/Consumer.java:257]: `DECAY` is final and used to decrease `mBadMessages` as before. It does not make sense to declare new `DECAY` variable on each `writeMessage` call, so I moved it to static final constant.

**Comment by pdambrauskas** [comment]
> The refactoring makes the code diff difficult to read, I wasn't sure the purpose of making those new methods. Looks like the main purpose of the PR is to add mBasMessages, you can just insert this logic in place. Also what kind of errors do you see during messageWriter.write and you want to skip those errors?

Hey Henry, thanks for taking time to review my  Pull Requests :). I do understand that it is hard to review this code, since the method was not that small.

`mBadMessages` was introduced to make it possible to ignore all failing messages, but it is not the main purpose of this PR. 

To simplify the idea, before code looked like this:
```java
//...
try {
  // parse partition
} catch (Exception e) {
  // increment consumer.message_errors.count metric
  // handle fail, re-throw if there were > 1000 errors 
}

try {
  // write message
} catch (Exception e) {
  // just re-throw
}
```
After this change there is only one `try` block:

```java
try {
  // parse partition
  // write message
} catch (Exception e) {
  // increment consumer.message_errors.count metric
  // handle fail, re-throw if there were > 1000 errors 
}
```
This allows us to configure secor to not fail on writes and also `onsumer.message_errors.count` is more correct.

> Also what kind of errors do you see during messageWriter.write and you want to skip those errors?

Our error is very similar to one, described in #1505. We use custom `ReaderWriterFactory` implementation with custom Writer to write json messages to parquet and validate schema, so exception is a bit different though, I thought it would make sense to catch exception in our Writer, but then I saw that others have the same problem on #1505. And `consumer.message_errors.count` metric is increased on Consumer class, so i decided to keep on place responsible for handling this kind of errors.

**Comment by HenryCaiHaiying** [comment]
Your explanation makes sense, I will merge in your PR, thanks.
